AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BookVerse Microservicios

Resources:
  BookVerseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DB_USER: "your_db_user"
          DB_PASSWORD: "your_db_password"
          DB_HOST: "your_db_host"
          DB_PORT: "your_db_port"
          DB_NAME: "your_db_name"
      Events:
        BookVerseApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  BookVerseApiUrl:
    Description: "API Gateway endpoint URL for BookVerse Microservicios"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
